version: '3.8'

services:
  bloger:
    build: .
    container_name: bloger
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./logs:/app/logs
    networks: 
      - bloger-network
networks:
  bloger-network:
    driver: bridge
